# Generated by Django 5.2 on 2025-04-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_role_user_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Groups",
        ),
    ]
