# Generated by Django 5.2 on 2025-05-02 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BootCampCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BootCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "bootcamp_type",
                    models.CharField(
                        choices=[("in_person", "حضوری"), ("online", "آنلاین")],
                        max_length=10,
                    ),
                ),
                (
                    "bootcamp_state",
                    models.CharField(
                        choices=[
                            ("pre_registration", "پیش\u200cثبت\u200cنام"),
                            ("registration_open", "در حال ثبت\u200cنام"),
                            ("in_progress", "در حال برگزاری"),
                            ("completed", "برگزار شده"),
                            ("canceled", "لغو شده"),
                        ],
                        default="pre_registration",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("day_time", models.TimeField()),
                ("day_of_weeks", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("price", models.PositiveBigIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bootcamps",
                        to="bootcamps.bootcampcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BootCampParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "دانشجو"),
                            ("teacher", "مدرس"),
                            ("mentor", "منتور"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "bootcamp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bootcamps.bootcamp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "bootcamp", "role")},
            },
        ),
        migrations.AddField(
            model_name="bootcamp",
            name="participants",
            field=models.ManyToManyField(
                related_name="bootcamp_roles",
                through="bootcamps.BootCampParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
