# Generated by Django 5.2 on 2025-05-02 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BootCampsJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("full", "پرداخت کامل"),
                            ("installment", "پرداخت اقساطی"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "bootCamp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bootcamps.bootcamp",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
