# Generated by Django 5.2 on 2025-05-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamps", "0002_bootcampsjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcampcategory",
            name="bootcamp_type",
            field=models.CharField(
                choices=[("in_person", "حضوری"), ("online", "آنلاین")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
