# Generated by Django 5.2 on 2025-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamps", "0003_bootcampcategory_bootcamp_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bootcampsjoinrequest",
            name="accepted",
        ),
        migrations.AddField(
            model_name="bootcampsjoinrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
