# Generated by Django 5.2 on 2025-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "درحال بررسی"),
                    ("answered", "پاسخ داده شده"),
                    ("unanswered", "پاسخ داده نشده"),
                    ("closed", "بسته شده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
