# Generated by Django 5.2 on 2025-05-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_ticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
    ]
