# Generated by Django 5.2 on 2025-05-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_remove_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ticket.ticket",
            ),
        ),
    ]
